name: Test Runner
on: [push]
permissions:
  contents: write
concurrency:
  group: lv2020
  cancel-in-progress: false
jobs:
  checkout:
    runs-on: lv2020
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
  build:
    needs: checkout
    runs-on: lv2020
    steps:
      - uses: astemes/astemes-github-actions/buildLVBuildSpec@main
        with:
          project-path: "source\\LUnit CLI.lvproj"
          build-spec: "LUnitCLI"
  release:
    needs: build
    runs-on: lv2020
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Get version
        id: get_version
        uses: astemes/astemes-github-actions/getVersion@main
      - name: Build VIP
        id: build-vip
        uses: astemes/astemes-github-actions/buildVIPackage@main
        with:
          vipb-path: "source\\LUnit CLI.vipb"
          lv-version: "20.0"
          pkg-version: "${{ steps.get_version.outputs.version }}"
      - name: Release VIP
        uses: astemes/astemes-github-actions/releaseFile@main
        with:
          file-path: "${{ steps.build-vip.outputs.artifact-path }}"